//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustodySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custody
    {
        public int Custody_ID { get; set; }
        public string Custody_Name { get; set; }
        public System.DateTime Added_Date { get; set; }
        public int Amount { get; set; }
        public int Available { get; set; }
        public int Given { get; set; }
        public bool Status { get; set; }
        public string Notes { get; set; }
        public string Custody_Color { get; set; }
        public string Custody_Type { get; set; }
    }
}
