//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustodySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public int Phone_No { get; set; }
        public string Department { get; set; }
        public string Job { get; set; }
        public string Access { get; set; }
        public Nullable<int> password { get; set; }
    }
}
